name: provider101
description: A new Flutter project covering use of Provider as a Flutter StateManagement approach with multiple examples.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 6.0.4
  go_router: 4.5.0
  http: 0.13.5
  dartz: 0.10.1
  get_it: 7.2.0
  equatable: 2.0.3
  flutter_html: ^2.2.1
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  mocktail: ^0.3.0
  mockito: ^5.3.2
  build_runner: ^2.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
